### ISSUE TITLE
bump overlay line width not preserved

### ISSUE THREAD

**Issue by thim81** [bump-sh/cli#579]
## Steps to reproduce
Using the `bump overlay` results in an unwanted line width.

Take any OpenAPI file, apply the following example overlay:

```yaml
overlay: 1.0.0
info:
  title: Structured Overlay
  version: 1.0.0
actions:
  - target: "$"   # Root of document
    update:
      info:
        x-overlay-applied: structured-overlay
      paths:
        "/":
          summary: "The root resource"
          get:
            summary: "Retrieve the root resource"
            x-rate-limit: 100
        /pets:
          get:
            summary: "Retrieve a list of pets"
            x-rate-limit: 100
#      components:
#      tags:
```

execute: `bump overlay openapi.yaml overlays.yaml > openapi.public.yaml`

## Expected behavior

Using the `bump overlay` results in the original line width being kept.

BEFORE/AFTER
![IMG-2024-09-10 at 14-28-47@2x](https://github.com/user-attachments/assets/2c833bae-13f3-417e-ae13-a9e46ad77cae)
