### ISSUE TITLE
bump overlay not merging parameters 

### ISSUE THREAD

**Issue by thim81** [bump-sh/cli#580]
## Steps to reproduce

Openapi.yaml
```yaml
openapi: 3.0.1
info:
  title: Datasource API
  description: API to work with Datasources.
  termsOfService: 'urn:tos'''
paths:
  /timeseries:
    get:
      operationId: searchTimeSeriesDefinitions
      summary: Search the time series definitions
      parameters:
        - name: searchPattern
          in: query
          description: Pattern to search time series definitions. Cannot be used at the same time as name parameter.
          required: false
          schema:
            type: string
```

overlays.yaml

```yaml
overlay: 1.0.0
info:
  title: Structured Overlay
  version: 1.0.0
actions:
  - target: "$"   # Root of document
    update:
      paths:
        /timeseries:
          get:
            description: Retrieve a list of all time series definitions. This endpoint supports search and pagination.
            parameters:
              - name: searchPattern
                in: query
                description: A pattern used to search time series definitions.
                schema:
                  example: temp-
````

execute: `bump overlay openapi.yaml overlays.yaml > openapi.public.yam`l

Result in:

```yaml
paths:
  /timeseries:
    get:
      operationId: searchTimeSeriesDefinitions
      summary: Search the time series definitions
      description: Retrieve a list of all time series definitions. This endpoint supports search and pagination.
      parameters:
        - name: searchPattern
          in: query
          description: Pattern to search time series definitions. Cannot be used at the same time as name parameter.
          required: false
          schema:
            type: string
        - name: searchPattern
          in: query
          description: A pattern used to search time series definitions.
          schema:
            example: temp*
```

## Expected result

```yaml
paths:
  /timeseries:
    get:
      operationId: searchTimeSeriesDefinitions
      summary: Search the time series definitions
      description: Retrieve a list of all time series definitions. This endpoint supports search and pagination.
      parameters:
        - name: searchPattern
          in: query
          description: A pattern used to search time series definitions.
          required: false
          schema:
            type: string
            example: temp-
```
